name: 'Push Build Information to Octopus Deploy'
description: 'GitHub Action to push build information to Octopus Deploy'
author: 'Octopus Deploy'
branding:
  color: 'blue'
  icon: 'package'

inputs:
  packages:
    description: 'A multi-line list of packages to push to Octopus Deploy.'
  version:
    description: 'The version of the package(s)'
  overwrite_mode:
    default: 'FailIfExists'
    description: 'Determines the action to perform with build information if it already exists in the repository. Valid values are "FailIfExists", "OverwriteExisting", and "IgnoreIfExists".'
  branch:
    description: 'The branch name, if omitted the GitHub ref will be used.'
  api_key:
    description: 'The API key used to access Octopus Deploy. You must provide an API key or username and password. If the guest account is enabled, a key of API-GUEST may be used. It is strongly recommended that this value retrieved from a GitHub secret.'
  server:
    description: 'The base URL hosting Octopus Deploy (i.e. "https://octopus.example.com/"). It is recommended to retrieve this value from an environment variable.'
  space:
    description: 'The name or ID of a space within which this command will be executed. If omitted, the default space will be used.'
  base_branch:
    description: 'The base branch to compare the commits to. If omitted only the last push commit will be used.'
  github_token:
    description: 'GitHub_Token used for API call. Used when base_branch is provided.'

runs:
  using: 'node20'
  main: 'dist/index.js'
