on:
  push:
    branches:
      - main
name: release-please
env:
  ACTION_NAME: push-build-information-action
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: github-release
          package-name: ${{env.ACTION_NAME}}
          release-type: node
