name: 'test-report'
on:
  workflow_run:
    workflows: ['build-test']
    types:
      - completed
jobs:
  report:
    # https://github.com/dorny/test-reporter/issues/168
    permissions:
      statuses: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          artifact: test-results
          name: JEST Tests
          path: '*.xml'
          reporter: jest-junit
